version: '2'
services:
  web:
    image: quartz/quartz
    hostname: quartz
    container_name: quartz
    # 指定时区时间，与系统时间时区一致
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - 5000:5000
    networks:
      default:
        ipv4_address: 172.18.0.7
    restart: always
    #时区方式一：
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    #时区方式二：
    #environment:
    #  - TZ=Asia/Shanghai
    #  配配自定义网络
    #network:
    #  mynetwork:
    #    ipv4_address: 172.18.0.4
    #volumes:
    #    - /data/spring-boot-jeewx/logs:/logs
    #network_mode: bridge  # 连接外部容器
    #env_file: ./common.env
    #extends:
    #  file: common.yml
    #  service: common

networks:
  default:
    external:
      name: mynetwork

# 创建自定义网络
#networks:
#  mynetwork:
#    ipam:
#      config:
#        - subnet: 172.18.0.0/16
#          gateway: 172.18.0.1

